name: NoPlayerFreeze
version: 2.0
main: me.cageydinosaur.noplayerfreeze.Main
api-version: 1.20.3
commands:
  noplayerfreeze:
    usage: /noplayerfreeze
    description: Help for the NoPlayerFreeze plugin