name: NoPlayerFreeze
version: 1.0
main: me.cageydinosaur.noplayerfreeze.Main
api-version: 1.20.3
commands:
  noplayerfreeze:
    usage: /noplayerfreeze
    description: Toggles freezing of the server when no non-afk players are online