name: NoPlayerFreeze
version: 1.0
main: me.cageydinosaur.noplayerfreeze.Main
api-version: 1.20.6
commands:
  noplayerfreeze:
    usage: /noplayerfreeze
    description: Toggles freezing of the ticks when no players are online